address_corrections = {
    "SANTA, RI, TA": "SANTA RITA",
    "SANTA,RI,TA": "SANTA RITA",
    "SANTA, RI , TA": "SANTA RITA",
    "SANTA, RI TA": "SANTA RITA",
    "RI, TA": "RITA",
    "RI,TA": "RITA",
    "RI , TA": "RITA",
    "RI TA": "RITA",
    "MINALINGSZAIPANGA": "MINALIN PAMPANGA",
    "MINALINGSZMIPANGA": "MINALIN PAMPANGA",
    "MINALINGIBSIPANGA": "MINALIN PAMPANGA",
    "PAMPAA, GA": "PAMPANGA",
    "PAMPAA , GA": "PAMPANGA",
    "PAMPAA GA": "PAMPANGA",
    "LAMBAG": "LAMBAC",
    "PAMPANGA, GA": "PAMPANGA",
    "MINALINZIBMIPANGA": "MINALIN PAMPANGA"
}
